### ISSUE TITLE
HW modding with BJT

### ISSUE THREAD

**Issue by goooroooX** [fergofrog/microwave_usb_fan#6]
Hi!

Can you please provide more details (specs and background) how to mod the fan with BJT to make it accept new messages on-the-fly?
Thank you!

**Comment by fergofrog** [comment]
I was ultimately unsuccessful at achieving the modification. It all worked outside of the case, but when I put it all together it died - presumably the BJT's base touched the outside and caused a short. I'd recommend you take care if attempting.

My hope was that by desoldering the push button that I'd be able to replace it with the BJT, the emitter and base replacing the button, as you can see in slides 57 and 58. I used a spare resistor in line with the BJT's base, which is taken high in order to toggle the motor on and off.
